<?php

namespace App\Service;

use App\Factory\DatabaseConnectionFactory;
use Doctrine\DBAL\Exception;

class ResetTmpDatabase
{
    public function __construct(private DatabaseConnectionFactory $databaseConnectionFactory)
    {
    }

    /**
     * @throws Exception
     */
    public function resetDatabase(): void
    {
        $connection = $this->databaseConnectionFactory->getSecondConnection();
        if (!$connection) {
            throw new Exception('Connection to TMP database failed');
        }

        $connection->beginTransaction();
        try {
            $connection->executeStatement($this->getScript());
            $connection->commit();
        } catch (Exception $e) {
            $connection->rollBack();
            throw $e;
        }
    }

    private function getScript(): string
    {
        return "
            SET statement_timeout = 0;
            SET lock_timeout = 0;
            SET idle_in_transaction_session_timeout = 0;
            SET client_encoding = 'UTF8';
            SET standard_conforming_strings = on;
            SELECT pg_catalog.set_config('search_path', '', false);
            SET check_function_bodies = false;
            SET xmloption = content;
            SET client_min_messages = warning;
            SET row_security = off;
            
            ALTER TABLE ONLY public.acc_interlock DROP CONSTRAINT fkwfqvs3co837rh43gp3gvntqg;
            ALTER TABLE ONLY public.att_shift_timeslot DROP CONSTRAINT fksurpmhjfwcbxtfc4fx5k8qubl;
            ALTER TABLE ONLY public.auth_biotemplate DROP CONSTRAINT fks8w7jafwatmi8r30drn7s8xbq;
            ALTER TABLE ONLY public.acc_door_verifymoderule DROP CONSTRAINT fks5y3m56mipy09659u342htk2d;
            ALTER TABLE ONLY public.vms_globallinkage_in DROP CONSTRAINT fkrkxsjv61nmnaxr9qmh2w3ab7m;
            ALTER TABLE ONLY public.vms_globallinkage_eleout DROP CONSTRAINT fkragkh17cs90hgcb8vkj1j4fje;
            ALTER TABLE ONLY public.att_device_option DROP CONSTRAINT fkr5dehf9o8in0r46a77porhwl1;
            ALTER TABLE ONLY public.auth_department DROP CONSTRAINT fkr3a1jtk03b8b186kpwqsvu6qc;
            ALTER TABLE ONLY public.acc_door_verifymoderule DROP CONSTRAINT fkr1yxqg0q4d8duyo5mn35kx468;
            ALTER TABLE ONLY public.vms_channel DROP CONSTRAINT fkr16j0u4qgop5xsngbht2ck63a;
            ALTER TABLE ONLY public.acc_verifymode_rule DROP CONSTRAINT fkqnktyyt9infpsdw0p8n1e46mj;
            ALTER TABLE ONLY public.pers_position DROP CONSTRAINT fkqm2361yu1rkpvd9a7i8wyw6fm;
            ALTER TABLE ONLY public.auth_role_permission DROP CONSTRAINT fkqgnjvxbqwtepqgvy9bgh37t6p;
            ALTER TABLE ONLY public.pers_person DROP CONSTRAINT fkq4iq5nbcea2g13jur5yanjouf;
            ALTER TABLE ONLY public.auth_area DROP CONSTRAINT fkpybeg1491dud0gkk77rrhboty;
            ALTER TABLE ONLY public.acc_linkage_inout DROP CONSTRAINT fkpww2ns8jcovujs8py6jkjmgm3;
            ALTER TABLE ONLY public.auth_user_role DROP CONSTRAINT fkptn1b1vvejcvel3tq402eyl2c;
            ALTER TABLE ONLY public.acc_linkage DROP CONSTRAINT fkpte45lm1favcr54897ssfv355;
            ALTER TABLE ONLY public.vms_globallinkage_vidout DROP CONSTRAINT fkp5ksu8k9ybsfcovddv0q4qgij;
            ALTER TABLE ONLY public.acc_antipassback DROP CONSTRAINT fkp2b9odgd8fkun25eukytc14mn;
            ALTER TABLE ONLY public.att_personsch_shift DROP CONSTRAINT fkox5iyumivlae2y9kxvrpr4nvk;
            ALTER TABLE ONLY public.acc_person_firstopen DROP CONSTRAINT fkow6oed0lc55057irhs9x2lxw6;
            ALTER TABLE ONLY public.vms_globallinkage_person DROP CONSTRAINT fkohaj0da1tgythvljmu58y40qd;
            ALTER TABLE ONLY public.acc_linkage_trigger DROP CONSTRAINT fko9nvqkyikti9xtsje95siqj7c;
            ALTER TABLE ONLY public.att_groupsch_shift DROP CONSTRAINT fknqdmd20fhmwfvb1h9mc4pfeqq;
            ALTER TABLE ONLY public.adms_device DROP CONSTRAINT fknjhdx30g2xkxl2tr1shxcjtk5;
            ALTER TABLE ONLY public.acc_device DROP CONSTRAINT fknip2dv63uttxi4tvqehuy0abg;
            ALTER TABLE ONLY public.acc_combopen_comb DROP CONSTRAINT fkn1w5dr14cj4pn3dg1at2o2weu;
            ALTER TABLE ONLY public.auth_user_role DROP CONSTRAINT fkn1lpth3d429d22yj3g9eg7743;
            ALTER TABLE ONLY public.att_deptsch_shift DROP CONSTRAINT fkmcdcas14atbtx0dklty112i3n;
            ALTER TABLE ONLY public.auth_user_dept DROP CONSTRAINT fkl61mxxa2rq36amgudy9yey1xc;
            ALTER TABLE ONLY public.att_cyclesch_shift DROP CONSTRAINT fkkpv75b1011mwgbf84gux2w7l6;
            ALTER TABLE ONLY public.base_print_param DROP CONSTRAINT fkkmfyytipp8qn4swj3tgsegaym;
            ALTER TABLE ONLY public.acc_device_verifymode DROP CONSTRAINT fkjqnhk2bud84vch8elqefsfois;
            ALTER TABLE ONLY public.vms_channel2entity DROP CONSTRAINT fkjf895mds6stgcco75dbl8sr5i;
            ALTER TABLE ONLY public.acc_linkage_media DROP CONSTRAINT fkiuxeh5snl5j3ygabl9fd4qky6;
            ALTER TABLE ONLY public.vms_linkage_event DROP CONSTRAINT fkiqvvcjcumy0tohvf3y3idxmho;
            ALTER TABLE ONLY public.acc_door DROP CONSTRAINT fkij25hiqkmug371vrk8pb3mwl4;
            ALTER TABLE ONLY public.att_personsch_shift DROP CONSTRAINT fki92tc6tx126m4csk1ijxx4vku;
            ALTER TABLE ONLY public.vms_blackwhite_person DROP CONSTRAINT fki5tu5q57edcmk4mxhxkrib8hm;
            ALTER TABLE ONLY public.acc_person_combopenperson DROP CONSTRAINT fki4pfqhd43k7b4308fioghmoav;
            ALTER TABLE ONLY public.acc_firstopen DROP CONSTRAINT fkhrwjmwsu6d5ljc5ihj1iecqst;
            ALTER TABLE ONLY public.auth_appmenus_children DROP CONSTRAINT fkh28dptlcb332ykrxim26nw64d;
            ALTER TABLE ONLY public.acc_linkage_vid DROP CONSTRAINT fkfone9gvjojx15lbci28somsvc;
            ALTER TABLE ONLY public.vms_globallinkage_accout DROP CONSTRAINT fkflv6cuerum11v65sys27ic0iy;
            ALTER TABLE ONLY public.acc_level_door DROP CONSTRAINT fkfg8k19rdvi7notbbdyjle2t2y;
            ALTER TABLE ONLY public.att_shift_timeslot DROP CONSTRAINT fkf6qxseej811svj0g2utxxq2k7;
            ALTER TABLE ONLY public.vms_globallinkage_media DROP CONSTRAINT fkf4jv1b7l7tq0qcqgu0q4avtne;
            ALTER TABLE ONLY public.att_tempsch_timeslot DROP CONSTRAINT fkejj8qcnkvw957jcrt4bqncwk0;
            ALTER TABLE ONLY public.vms_blackwhite_person DROP CONSTRAINT fkeigl5q9ju27s175q5hqw4x4tl;
            ALTER TABLE ONLY public.acc_auxin DROP CONSTRAINT fkeg6f6ahwru2hcoxtpjiqiuqa6;
            ALTER TABLE ONLY public.base_dictionary_value DROP CONSTRAINT fke5i41ofoctd1bw4fstp1myhk7;
            ALTER TABLE ONLY public.acc_level_dept DROP CONSTRAINT fke3ky6tbwc0d72kdnmqajkb9yc;
            ALTER TABLE ONLY public.auth_user_area DROP CONSTRAINT fkdui22g2jpmv5vj6q9rhnaxq0v;
            ALTER TABLE ONLY public.acc_linkage_trigger DROP CONSTRAINT fkdmspf0x7clsj6xhfprd8fkvck;
            ALTER TABLE ONLY public.acc_device DROP CONSTRAINT fkdfv0sd0sw96cqrr7w72eprqpg;
            ALTER TABLE ONLY public.auth_permission DROP CONSTRAINT fkbiyhkakl58d4fh1urfoya49hr;
            ALTER TABLE ONLY public.pers_biotemplate DROP CONSTRAINT fkahx9s0vyy2xo3krtcx8i7jn32;
            ALTER TABLE ONLY public.att_groupsch_shift DROP CONSTRAINT fka0ejlkrjla6nd77q4udvspe54;
            ALTER TABLE ONLY public.acc_auxout DROP CONSTRAINT fk9xf46nfyn58l9mywf6dgnpris;
            ALTER TABLE ONLY public.base_lang_res DROP CONSTRAINT fk9lkgvbb025ltfm0yj0sia736s;
            ALTER TABLE ONLY public.acc_linkage_index DROP CONSTRAINT fk9gtnellqindkb4ax2lsdo66b2;
            ALTER TABLE ONLY public.acc_person_verifymoderule DROP CONSTRAINT fk9fhwk15nfl40mdspl5s6ax0y4;
            ALTER TABLE ONLY public.att_tempsch_timeslot DROP CONSTRAINT fk8ld2enouyl8uq95qs66xes7ga;
            ALTER TABLE ONLY public.acc_device_event DROP CONSTRAINT fk7ujak66jah2h4uj5el9w2gbmn;
            ALTER TABLE ONLY public.auth_role_permission DROP CONSTRAINT fk7ndbee91kroysycq5ddjjnipn;
            ALTER TABLE ONLY public.acc_level_door DROP CONSTRAINT fk7lcv6jt9umrqpoa8p214y71r4;
            ALTER TABLE ONLY public.att_timeslot_breaktime DROP CONSTRAINT fk7dxil57g98naulbvb4iexuln5;
            ALTER TABLE ONLY public.acc_combopen_door DROP CONSTRAINT fk6dsxivrxlaf4fjy1bokvdkgkd;
            ALTER TABLE ONLY public.att_timeslot_breaktime DROP CONSTRAINT fk680qwdp44xp4f0r62lnav0tpv;
            ALTER TABLE ONLY public.acc_combopen_comb DROP CONSTRAINT fk5kmcm8ah8yq0qygso0fgkgq17;
            ALTER TABLE ONLY public.att_deptsch_shift DROP CONSTRAINT fk5d5qgvs1263b15p92w3a2bmh1;
            ALTER TABLE ONLY public.auth_user_area DROP CONSTRAINT fk4jf35nor20xjx9csafgwsok1b;
            ALTER TABLE ONLY public.att_cyclesch_shift DROP CONSTRAINT fk4hp2s7odag0qrkytmwwpw03s8;
            ALTER TABLE ONLY public.acc_reader DROP CONSTRAINT fk4amwipjfr1whp1qij3eoig8ss;
            ALTER TABLE ONLY public.pers_personchange DROP CONSTRAINT fk46f95ui8qika6f2dp65dekrm2;
            ALTER TABLE ONLY public.acc_map_pos DROP CONSTRAINT fk41sbaug4prlkwnfajbxi2nm4e;
            ALTER TABLE ONLY public.adms_device_option DROP CONSTRAINT fk3vu767epp0m4l4plhyv2wseu6;
            ALTER TABLE ONLY public.vms_globallinkage_trigger DROP CONSTRAINT fk3ej97t4tgwheuk3n4rr3qlps6;
            ALTER TABLE ONLY public.acc_level_person DROP CONSTRAINT fk3cscnldk4c7m3fn9mjvbacyon;
            ALTER TABLE ONLY public.acc_reader_option DROP CONSTRAINT fk2sh3f9pm1s14wfdd2aqkoh4ac;
            ALTER TABLE ONLY public.acc_device_option DROP CONSTRAINT fk284w6cip61mpimmfgh11dfhvp;
            ALTER TABLE ONLY public.pers_certificate DROP CONSTRAINT fk1gmovwx4rytre52uyitjevjam;
            ALTER TABLE ONLY public.auth_user_dept DROP CONSTRAINT fk17gxgrsc0fh91kbarbwdhr3fp;
            DROP INDEX public.vms_link_upt_idx;
            DROP INDEX public.vms_link_crt_idx;
            DROP INDEX public.pers_physical_no_idx;
            DROP INDEX public.pers_person_update_time_idx;
            DROP INDEX public.pers_person_pin_idx;
            DROP INDEX public.pers_person_name_idx;
            DROP INDEX public.pers_person_dept_id_idx;
            DROP INDEX public.pers_person_create_time_idx;
            DROP INDEX public.pers_logical_card_no_idx;
            DROP INDEX public.pers_link_create_time_idx;
            DROP INDEX public.pers_leaveperson_pin_idx;
            DROP INDEX public.pers_leaveperson_name_idx;
            DROP INDEX public.pers_leaveperson_dept_id_idx;
            DROP INDEX public.pers_identity_card_idcard_idx;
            DROP INDEX public.pers_card_update_time_idx;
            DROP INDEX public.pers_card_person_pin_idx;
            DROP INDEX public.pers_card_person_id_idx;
            DROP INDEX public.pers_card_no_idx;
            DROP INDEX public.pers_card_create_time_idx;
            DROP INDEX public.pers_bio_template_pin_idx;
            DROP INDEX public.pers_attribute_attr_name_idx;
            DROP INDEX public.pers_attr_ext_create_time_idx;
            DROP INDEX public.hep_transaction_upt_idx;
            DROP INDEX public.hep_transaction_pin_idx;
            DROP INDEX public.hep_transaction_evd_idx;
            DROP INDEX public.hep_transaction_dept_idx;
            DROP INDEX public.hep_transaction_crt_idx;
            DROP INDEX public.base_oplog_update_time_idx;
            DROP INDEX public.base_oplog_create_time_idx;
            DROP INDEX public.auth_user_upt_idx;
            DROP INDEX public.auth_user_crt_idx;
            DROP INDEX public.auth_role_upt_time_idx;
            DROP INDEX public.auth_role_crt_time_idx;
            DROP INDEX public.auth_permission_upt_time_idx;
            DROP INDEX public.auth_permission_crt_time_idx;
            DROP INDEX public.auth_department_upt_idx;
            DROP INDEX public.auth_department_crt_idx;
            DROP INDEX public.auth_company_upt_idx;
            DROP INDEX public.auth_company_crt_idx;
            DROP INDEX public.auth_area_upt_idx;
            DROP INDEX public.auth_area_crt_idx;
            DROP INDEX public.auth_app_upt_idx;
            DROP INDEX public.auth_app_crt_idx;
            DROP INDEX public.att_tran_pin_datetime_idx;
            DROP INDEX public.att_tran_device_id_idx;
            DROP INDEX public.att_tran_dept_id_idx;
            DROP INDEX public.att_tran_att_date_idx;
            DROP INDEX public.att_record_pers_pin_idx;
            DROP INDEX public.att_record_dept_id_idx;
            DROP INDEX public.att_record_att_date_idx;
            DROP INDEX public.att_pers_person_pin_idx;
            DROP INDEX public.att_pers_person_id_idx;
            DROP INDEX public.att_pers_group_id_idx;
            DROP INDEX public.att_pers_dept_id_idx;
            DROP INDEX public.att_device_op_log_upt_idx;
            DROP INDEX public.att_device_op_log_crt_idx;
            DROP INDEX public.att_day_card_person_pin_idx;
            DROP INDEX public.att_day_card_dept_id_idx;
            DROP INDEX public.att_day_card_att_date_idx;
            DROP INDEX public.att_ar_upt_idx;
            DROP INDEX public.att_ar_crt_idx;
            DROP INDEX public.adms_devcmd_update_time_idx;
            DROP INDEX public.adms_devcmd_create_time_idx;
            DROP INDEX public.acc_transaction_upt_idx;
            DROP INDEX public.acc_transaction_evt_idx;
            DROP INDEX public.acc_transaction_crt_idx;
            ALTER TABLE ONLY public.vms_videointercom_transaction DROP CONSTRAINT vms_videointercom_transaction_pkey;
            ALTER TABLE ONLY public.vms_user DROP CONSTRAINT vms_user_pkey;
            ALTER TABLE ONLY public.vms_transaction DROP CONSTRAINT vms_transaction_pkey;
            ALTER TABLE ONLY public.vms_search_image DROP CONSTRAINT vms_search_image_pkey;
            ALTER TABLE ONLY public.vms_report DROP CONSTRAINT vms_report_pkey;
            ALTER TABLE ONLY public.vms_person DROP CONSTRAINT vms_person_pkey;
            ALTER TABLE ONLY public.vms_monotoring DROP CONSTRAINT vms_monotoring_pkey;
            ALTER TABLE ONLY public.vms_linkage_event DROP CONSTRAINT vms_linkage_event_pkey;
            ALTER TABLE ONLY public.vms_link DROP CONSTRAINT vms_link_pkey;
            ALTER TABLE ONLY public.vms_globallinkage_vidout DROP CONSTRAINT vms_globallinkage_vidout_pkey;
            ALTER TABLE ONLY public.vms_globallinkage_trigger DROP CONSTRAINT vms_globallinkage_trigger_pkey;
            ALTER TABLE ONLY public.vms_globallinkage DROP CONSTRAINT vms_globallinkage_pkey;
            ALTER TABLE ONLY public.vms_globallinkage_person DROP CONSTRAINT vms_globallinkage_person_pkey;
            ALTER TABLE ONLY public.vms_globallinkage_media DROP CONSTRAINT vms_globallinkage_media_pkey;
            ALTER TABLE ONLY public.vms_globallinkage_in DROP CONSTRAINT vms_globallinkage_in_pkey;
            ALTER TABLE ONLY public.vms_globallinkage_eleout DROP CONSTRAINT vms_globallinkage_eleout_pkey;
            ALTER TABLE ONLY public.vms_globallinkage_accout DROP CONSTRAINT vms_globallinkage_accout_pkey;
            ALTER TABLE ONLY public.vms_distribute_record DROP CONSTRAINT vms_distribute_record_pkey;
            ALTER TABLE ONLY public.vms_distribute DROP CONSTRAINT vms_distribute_pkey;
            ALTER TABLE ONLY public.vms_device DROP CONSTRAINT vms_device_pkey;
            ALTER TABLE ONLY public.vms_channel DROP CONSTRAINT vms_channel_pkey;
            ALTER TABLE ONLY public.vms_channel2entity DROP CONSTRAINT vms_channel2entity_pkey;
            ALTER TABLE ONLY public.vms_capture DROP CONSTRAINT vms_capture_pkey;
            ALTER TABLE ONLY public.vms_blackwhite DROP CONSTRAINT vms_blackwhite_pkey;
            ALTER TABLE ONLY public.vms_blackwhite_person DROP CONSTRAINT vms_blackwhite_person_pkey;
            ALTER TABLE ONLY public.vms_area DROP CONSTRAINT vms_area_pkey;
            ALTER TABLE ONLY public.auth_biotemplate DROP CONSTRAINT ukmre3ab7lhqg077xv3hil86drs;
            ALTER TABLE ONLY public.auth_user DROP CONSTRAINT uk_t1iph3dfc25ukwcl9xemtnojn;
            ALTER TABLE ONLY public.base_dictionary DROP CONSTRAINT uk_t12cl0q8u2dybvlcqrprd5o4x;
            ALTER TABLE ONLY public.auth_permission DROP CONSTRAINT uk_somba37al7jncqwbq818vx13e;
            ALTER TABLE ONLY public.acc_linkage DROP CONSTRAINT uk_s23p1gv638qvvrmvuir9wo734;
            ALTER TABLE ONLY public.adms_product DROP CONSTRAINT uk_prajknbeu36wyvs24gow7ke4;
            ALTER TABLE ONLY public.att_device DROP CONSTRAINT uk_lecu7g79dnliep6acav6syi2k;
            ALTER TABLE ONLY public.auth_role DROP CONSTRAINT uk_lc1sij60969nsgl5cy8bfgbsm;
            ALTER TABLE ONLY public.vms_user DROP CONSTRAINT uk_khcsnnhb4huw25s64heqqf4v4;
            ALTER TABLE ONLY public.auth_role DROP CONSTRAINT uk_k8dhmc0q3l9h59gv9gjeokib0;
            ALTER TABLE ONLY public.auth_appmenus DROP CONSTRAINT uk_k7xpxqqlj7vauwkijm5jou30l;
            ALTER TABLE ONLY public.base_print_template DROP CONSTRAINT uk_ie7bwyfnnve31rn9rx18cx97e;
            ALTER TABLE ONLY public.adms_product DROP CONSTRAINT uk_hnawxfb2d0g93j90kgjfoktqy;
            ALTER TABLE ONLY public.acc_timeseg DROP CONSTRAINT uk_hfqc9813m08be9g0ux6iysii3;
            ALTER TABLE ONLY public.acc_combopen_door DROP CONSTRAINT uk_h148fwstgj00d1wlt139h5h0h;
            ALTER TABLE ONLY public.base_sysparam DROP CONSTRAINT uk_g08ppis9a0u7vpbj80ntlfgub;
            ALTER TABLE ONLY public.acc_device DROP CONSTRAINT uk_fmtd6p858bsk1ji0fewp9abbt;
            ALTER TABLE ONLY public.auth_appmenus_children DROP CONSTRAINT uk_ep9nn3yiec9rr86ioj867av9d;
            ALTER TABLE ONLY public.acc_verifymode_rule DROP CONSTRAINT uk_e6qhn2tjje3dfmm23qjoj84m7;
            ALTER TABLE ONLY public.acc_device DROP CONSTRAINT uk_d8a4xa2owwf0jqwujfuy6u792;
            ALTER TABLE ONLY public.vms_device DROP CONSTRAINT uk_d2763vekyoaccyl0i01mftve7;
            ALTER TABLE ONLY public.adms_devcmd DROP CONSTRAINT uk_cierhu13xc1fnkjk0x4q6a3e5;
            ALTER TABLE ONLY public.pers_attribute_ext DROP CONSTRAINT uk_bj1elop932qr3tapsa9mvwbfb;
            ALTER TABLE ONLY public.acc_interlock DROP CONSTRAINT uk_a9ndse24x6wt65yb3nxhl18a9;
            ALTER TABLE ONLY public.pers_person DROP CONSTRAINT uk_9978vgq9hn4maey4p7qgeveuu;
            ALTER TABLE ONLY public.adms_auth_device DROP CONSTRAINT uk_6mxpbo7wi85ohfvq3d3mqthp2;
            ALTER TABLE ONLY public.acc_transaction DROP CONSTRAINT uk_6b0x8u1iijbubj0jol10j9hp9;
            ALTER TABLE ONLY public.vms_area DROP CONSTRAINT uk_62fl6ar8mcrgpplsl54annj;
            ALTER TABLE ONLY public.acc_combopen_person DROP CONSTRAINT uk_4nlhvlcg0rl27av22qg9uf0hl;
            ALTER TABLE ONLY public.adms_device DROP CONSTRAINT uk_4htmckwchmjk0jpqcr1jaudms;
            ALTER TABLE ONLY public.acc_ext_device DROP CONSTRAINT uk_4a25gboc68vkyln9ust82g0m1;
            ALTER TABLE ONLY public.acc_combopen_door DROP CONSTRAINT uk_45qg7eyjsse4du0iek4x935ih;
            ALTER TABLE ONLY public.acc_combopen_person DROP CONSTRAINT uk_1wv0p53g9b2yucywittx2kodi;
            ALTER TABLE ONLY public.pers_attribute DROP CONSTRAINT uk_1ignxhqi9dks8htttog87lxgb;
            ALTER TABLE ONLY public.system_module_info DROP CONSTRAINT system_module_info_pkey;
            ALTER TABLE ONLY public.system_client_info DROP CONSTRAINT system_client_info_pkey;
            ALTER TABLE ONLY public.pers_wiegandfmt DROP CONSTRAINT pers_wiegandfmt_pkey;
            ALTER TABLE ONLY public.pers_wiegandfmt_bid DROP CONSTRAINT pers_wiegandfmt_bid_pkey;
            ALTER TABLE ONLY public.pers_temp_person DROP CONSTRAINT pers_temp_person_pkey;
            ALTER TABLE ONLY public.pers_position DROP CONSTRAINT pers_position_pkey;
            ALTER TABLE ONLY public.pers_person_link DROP CONSTRAINT pers_pid_type_link_id_uq;
            ALTER TABLE ONLY public.pers_personchange DROP CONSTRAINT pers_personchange_pkey;
            ALTER TABLE ONLY public.pers_person DROP CONSTRAINT pers_person_pkey;
            ALTER TABLE ONLY public.pers_person_link DROP CONSTRAINT pers_person_link_pkey;
            ALTER TABLE ONLY public.pers_leaveperson DROP CONSTRAINT pers_leaveperson_pkey;
            ALTER TABLE ONLY public.pers_issuecard DROP CONSTRAINT pers_issuecard_pkey;
            ALTER TABLE ONLY public.pers_identity_card_info DROP CONSTRAINT pers_identity_card_info_pkey;
            ALTER TABLE ONLY public.pers_biotemplate DROP CONSTRAINT pers_id_type_ver_no_index_uq;
            ALTER TABLE ONLY public.pers_certificate DROP CONSTRAINT pers_certificate_pkey;
            ALTER TABLE ONLY public.pers_card DROP CONSTRAINT pers_card_pkey;
            ALTER TABLE ONLY public.pers_biotemplate DROP CONSTRAINT pers_biotemplate_pkey;
            ALTER TABLE ONLY public.pers_attribute DROP CONSTRAINT pers_attribute_pkey;
            ALTER TABLE ONLY public.pers_attribute_ext DROP CONSTRAINT pers_attribute_ext_pkey;
            ALTER TABLE ONLY public.hep_transaction DROP CONSTRAINT hep_transaction_pkey;
            ALTER TABLE ONLY public.hep_autoexport DROP CONSTRAINT hep_autoexport_pkey;
            ALTER TABLE ONLY public.data_source DROP CONSTRAINT data_source_pkey;
            ALTER TABLE ONLY public.base_sysparam DROP CONSTRAINT base_sysparam_pkey;
            ALTER TABLE ONLY public.base_register DROP CONSTRAINT base_register_pkey;
            ALTER TABLE ONLY public.base_print_template DROP CONSTRAINT base_print_template_pkey;
            ALTER TABLE ONLY public.base_print_param DROP CONSTRAINT base_print_param_pkey;
            ALTER TABLE ONLY public.base_oplog DROP CONSTRAINT base_oplog_pkey;
            ALTER TABLE ONLY public.base_message DROP CONSTRAINT base_message_pkey;
            ALTER TABLE ONLY public.base_media_file DROP CONSTRAINT base_media_file_pkey;
            ALTER TABLE ONLY public.base_mail DROP CONSTRAINT base_mail_pkey;
            ALTER TABLE ONLY public.base_language DROP CONSTRAINT base_language_pkey;
            ALTER TABLE ONLY public.base_lang_res DROP CONSTRAINT base_lang_res_pkey;
            ALTER TABLE ONLY public.base_dictionary_value DROP CONSTRAINT base_dictionary_value_pkey;
            ALTER TABLE ONLY public.base_dictionary DROP CONSTRAINT base_dictionary_pkey;
            ALTER TABLE ONLY public.base_dbbackup DROP CONSTRAINT base_dbbackup_pkey;
            ALTER TABLE ONLY public.auth_user_role DROP CONSTRAINT auth_user_role_pkey;
            ALTER TABLE ONLY public.auth_user DROP CONSTRAINT auth_user_pkey;
            ALTER TABLE ONLY public.auth_user_dept DROP CONSTRAINT auth_user_dept_pkey;
            ALTER TABLE ONLY public.auth_user_area DROP CONSTRAINT auth_user_area_pkey;
            ALTER TABLE ONLY public.auth_security_param DROP CONSTRAINT auth_security_param_pkey;
            ALTER TABLE ONLY public.auth_role DROP CONSTRAINT auth_role_pkey;
            ALTER TABLE ONLY public.auth_role_permission DROP CONSTRAINT auth_role_permission_pkey;
            ALTER TABLE ONLY public.auth_permission DROP CONSTRAINT auth_permission_pkey;
            ALTER TABLE ONLY public.auth_department DROP CONSTRAINT auth_department_pkey;
            ALTER TABLE ONLY public.auth_company DROP CONSTRAINT auth_company_pkey;
            ALTER TABLE ONLY public.auth_biotemplate DROP CONSTRAINT auth_biotemplate_pkey;
            ALTER TABLE ONLY public.auth_area DROP CONSTRAINT auth_area_pkey;
            ALTER TABLE ONLY public.auth_appmenus DROP CONSTRAINT auth_appmenus_pkey;
            ALTER TABLE ONLY public.auth_appmenus_children DROP CONSTRAINT auth_appmenus_children_pkey;
            ALTER TABLE ONLY public.auth_app DROP CONSTRAINT auth_app_pkey;
            ALTER TABLE ONLY public.auth_api_token DROP CONSTRAINT auth_api_token_pkey;
            ALTER TABLE ONLY public.att_trip DROP CONSTRAINT att_trip_pkey;
            ALTER TABLE ONLY public.att_transaction DROP CONSTRAINT att_transaction_pkey;
            ALTER TABLE ONLY public.att_timing DROP CONSTRAINT att_timing_pkey;
            ALTER TABLE ONLY public.att_timeslot DROP CONSTRAINT att_timeslot_pkey;
            ALTER TABLE ONLY public.att_timeslot_breaktime DROP CONSTRAINT att_timeslot_breaktime_pkey;
            ALTER TABLE ONLY public.att_tempsch_timeslot DROP CONSTRAINT att_tempsch_timeslot_pkey;
            ALTER TABLE ONLY public.att_tempsch DROP CONSTRAINT att_tempsch_pkey;
            ALTER TABLE ONLY public.att_sign DROP CONSTRAINT att_sign_pkey;
            ALTER TABLE ONLY public.att_sign_address DROP CONSTRAINT att_sign_address_pkey;
            ALTER TABLE ONLY public.att_sign_address_area DROP CONSTRAINT att_sign_address_area_pkey;
            ALTER TABLE ONLY public.att_shift_timeslot DROP CONSTRAINT att_shift_timeslot_pkey;
            ALTER TABLE ONLY public.att_shift DROP CONSTRAINT att_shift_pkey;
            ALTER TABLE ONLY public.att_record DROP CONSTRAINT att_record_pkey;
            ALTER TABLE ONLY public.att_point DROP CONSTRAINT att_point_pkey;
            ALTER TABLE ONLY public.att_personsch_shift DROP CONSTRAINT att_personsch_shift_pkey;
            ALTER TABLE ONLY public.att_personsch DROP CONSTRAINT att_personsch_pkey;
            ALTER TABLE ONLY public.att_person DROP CONSTRAINT att_person_pkey;
            ALTER TABLE ONLY public.att_overtime DROP CONSTRAINT att_overtime_pkey;
            ALTER TABLE ONLY public.att_out DROP CONSTRAINT att_out_pkey;
            ALTER TABLE ONLY public.att_leavetype DROP CONSTRAINT att_leavetype_pkey;
            ALTER TABLE ONLY public.att_leave DROP CONSTRAINT att_leave_pkey;
            ALTER TABLE ONLY public.att_holiday DROP CONSTRAINT att_holiday_pkey;
            ALTER TABLE ONLY public.att_groupsch_shift DROP CONSTRAINT att_groupsch_shift_pkey;
            ALTER TABLE ONLY public.att_groupsch DROP CONSTRAINT att_groupsch_pkey;
            ALTER TABLE ONLY public.att_group DROP CONSTRAINT att_group_pkey;
            ALTER TABLE ONLY public.att_group_person DROP CONSTRAINT att_group_person_pkey;
            ALTER TABLE ONLY public.att_device DROP CONSTRAINT att_device_pkey;
            ALTER TABLE ONLY public.att_device_option DROP CONSTRAINT att_device_option_pkey;
            ALTER TABLE ONLY public.att_device_op_log DROP CONSTRAINT att_device_op_log_pkey;
            ALTER TABLE ONLY public.att_deptsch_shift DROP CONSTRAINT att_deptsch_shift_pkey;
            ALTER TABLE ONLY public.att_deptsch DROP CONSTRAINT att_deptsch_pkey;
            ALTER TABLE ONLY public.att_day_card_detail DROP CONSTRAINT att_day_card_detail_pkey;
            ALTER TABLE ONLY public.att_cyclesch_shift DROP CONSTRAINT att_cyclesch_shift_pkey;
            ALTER TABLE ONLY public.att_cyclesch DROP CONSTRAINT att_cyclesch_pkey;
            ALTER TABLE ONLY public.att_custom_rule DROP CONSTRAINT att_custom_rule_pkey;
            ALTER TABLE ONLY public.att_custom_rule_org DROP CONSTRAINT att_custom_rule_org_pkey;
            ALTER TABLE ONLY public.att_class DROP CONSTRAINT att_class_pkey;
            ALTER TABLE ONLY public.att_break_time DROP CONSTRAINT att_break_time_pkey;
            ALTER TABLE ONLY public.att_autoexport DROP CONSTRAINT att_autoexport_pkey;
            ALTER TABLE ONLY public.att_area_person DROP CONSTRAINT att_area_person_pkey;
            ALTER TABLE ONLY public.att_area_person DROP CONSTRAINT att_area_person_area_pers;
            ALTER TABLE ONLY public.att_adjust DROP CONSTRAINT att_adjust_pkey;
            ALTER TABLE ONLY public.adms_product DROP CONSTRAINT adms_product_pkey;
            ALTER TABLE ONLY public.adms_pos_full_log DROP CONSTRAINT adms_pos_full_log_pkey;
            ALTER TABLE ONLY public.adms_pos_buy_log DROP CONSTRAINT adms_pos_buy_log_pkey;
            ALTER TABLE ONLY public.adms_pos_allow_log DROP CONSTRAINT adms_pos_allow_log_pkey;
            ALTER TABLE ONLY public.adms_device DROP CONSTRAINT adms_device_pkey;
            ALTER TABLE ONLY public.adms_device_option DROP CONSTRAINT adms_device_option_pkey;
            ALTER TABLE ONLY public.adms_devcmd DROP CONSTRAINT adms_devcmd_pkey;
            ALTER TABLE ONLY public.adms_cmd_id DROP CONSTRAINT adms_cmd_id_pkey;
            ALTER TABLE ONLY public.adms_auth_device DROP CONSTRAINT adms_auth_device_pkey;
            ALTER TABLE ONLY public.adms_att_device_log DROP CONSTRAINT adms_att_device_log_pkey;
            ALTER TABLE ONLY public.adms_acc_device_log DROP CONSTRAINT adms_acc_device_log_pkey;
            ALTER TABLE ONLY public.acc_verifymode_rule DROP CONSTRAINT acc_verifymode_rule_pkey;
            ALTER TABLE ONLY public.acc_transaction DROP CONSTRAINT acc_transaction_pkey;
            ALTER TABLE ONLY public.acc_topdoor_by_person DROP CONSTRAINT acc_topdoor_by_person_pkey;
            ALTER TABLE ONLY public.acc_timeseg DROP CONSTRAINT acc_timeseg_pkey;
            ALTER TABLE ONLY public.acc_timeseg_bid DROP CONSTRAINT acc_timeseg_bid_pkey;
            ALTER TABLE ONLY public.acc_reader DROP CONSTRAINT acc_reader_pkey;
            ALTER TABLE ONLY public.acc_reader_option DROP CONSTRAINT acc_reader_option_pkey;
            ALTER TABLE ONLY public.acc_person_verifymoderule DROP CONSTRAINT acc_person_verifymoderule_pkey;
            ALTER TABLE ONLY public.acc_person DROP CONSTRAINT acc_person_pkey;
            ALTER TABLE ONLY public.acc_person_lastaddr DROP CONSTRAINT acc_person_lastaddr_pkey;
            ALTER TABLE ONLY public.acc_person_firstopen DROP CONSTRAINT acc_person_firstopen_pkey;
            ALTER TABLE ONLY public.acc_person_combopenperson DROP CONSTRAINT acc_person_combopenperson_pkey;
            ALTER TABLE ONLY public.acc_map_pos DROP CONSTRAINT acc_map_pos_pkey;
            ALTER TABLE ONLY public.acc_map DROP CONSTRAINT acc_map_pkey;
            ALTER TABLE ONLY public.acc_linkage_vid DROP CONSTRAINT acc_linkage_vid_pkey;
            ALTER TABLE ONLY public.acc_linkage_trigger DROP CONSTRAINT acc_linkage_trigger_pkey;
            ALTER TABLE ONLY public.acc_linkage DROP CONSTRAINT acc_linkage_pkey;
            ALTER TABLE ONLY public.acc_linkage_media DROP CONSTRAINT acc_linkage_media_pkey;
            ALTER TABLE ONLY public.acc_linkage_inout DROP CONSTRAINT acc_linkage_inout_pkey;
            ALTER TABLE ONLY public.acc_linkage_index DROP CONSTRAINT acc_linkage_index_pkey;
            ALTER TABLE ONLY public.acc_level DROP CONSTRAINT acc_level_pkey;
            ALTER TABLE ONLY public.acc_level_person DROP CONSTRAINT acc_level_person_pkey;
            ALTER TABLE ONLY public.acc_level_door DROP CONSTRAINT acc_level_door_pkey;
            ALTER TABLE ONLY public.acc_level_dept DROP CONSTRAINT acc_level_dept_pkey;
            ALTER TABLE ONLY public.acc_interlock DROP CONSTRAINT acc_interlock_pkey;
            ALTER TABLE ONLY public.acc_holiday DROP CONSTRAINT acc_holiday_pkey;
            ALTER TABLE ONLY public.acc_firstopen DROP CONSTRAINT acc_firstopen_pkey;
            ALTER TABLE ONLY public.acc_firstin_lastout DROP CONSTRAINT acc_firstin_lastout_pkey;
            ALTER TABLE ONLY public.acc_ext_device DROP CONSTRAINT acc_ext_device_pkey;
            ALTER TABLE ONLY public.acc_dstime DROP CONSTRAINT acc_dstime_pkey;
            ALTER TABLE ONLY public.acc_dstime_bid DROP CONSTRAINT acc_dstime_bid_pkey;
            ALTER TABLE ONLY public.acc_door_verifymoderule DROP CONSTRAINT acc_door_verifymoderule_pkey;
            ALTER TABLE ONLY public.acc_door DROP CONSTRAINT acc_door_pkey;
            ALTER TABLE ONLY public.acc_device_verifymode DROP CONSTRAINT acc_device_verifymode_pkey;
            ALTER TABLE ONLY public.acc_device DROP CONSTRAINT acc_device_pkey;
            ALTER TABLE ONLY public.acc_device_option DROP CONSTRAINT acc_device_option_pkey;
            ALTER TABLE ONLY public.acc_device_event DROP CONSTRAINT acc_device_event_pkey;
            ALTER TABLE ONLY public.acc_device_bid DROP CONSTRAINT acc_device_bid_pkey;
            ALTER TABLE ONLY public.acc_combopenperson_bid DROP CONSTRAINT acc_combopenperson_bid_pkey;
            ALTER TABLE ONLY public.acc_combopendoor_bid DROP CONSTRAINT acc_combopendoor_bid_pkey;
            ALTER TABLE ONLY public.acc_combopen_person DROP CONSTRAINT acc_combopen_person_pkey;
            ALTER TABLE ONLY public.acc_combopen_door DROP CONSTRAINT acc_combopen_door_pkey;
            ALTER TABLE ONLY public.acc_combopen_comb DROP CONSTRAINT acc_combopen_comb_pkey;
            ALTER TABLE ONLY public.acc_auxout DROP CONSTRAINT acc_auxout_pkey;
            ALTER TABLE ONLY public.acc_auxin DROP CONSTRAINT acc_auxin_pkey;
            ALTER TABLE ONLY public.acc_antipassback DROP CONSTRAINT acc_antipassback_pkey;
            ALTER TABLE ONLY public.acc_alarm_monitor DROP CONSTRAINT acc_alarm_monitor_pkey;
            DROP TABLE public.vms_videointercom_transaction;
            DROP TABLE public.vms_user;
            DROP TABLE public.vms_transaction;
            DROP TABLE public.vms_search_image;
            DROP TABLE public.vms_report;
            DROP TABLE public.vms_person;
            DROP TABLE public.vms_monotoring;
            DROP TABLE public.vms_linkage_event;
            DROP TABLE public.vms_link;
            DROP TABLE public.vms_globallinkage_vidout;
            DROP TABLE public.vms_globallinkage_trigger;
            DROP TABLE public.vms_globallinkage_person;
            DROP TABLE public.vms_globallinkage_media;
            DROP TABLE public.vms_globallinkage_in;
            DROP TABLE public.vms_globallinkage_eleout;
            DROP TABLE public.vms_globallinkage_accout;
            DROP TABLE public.vms_globallinkage;
            DROP TABLE public.vms_distribute_record;
            DROP TABLE public.vms_distribute;
            DROP TABLE public.vms_device;
            DROP TABLE public.vms_channel2entity;
            DROP TABLE public.vms_channel;
            DROP TABLE public.vms_capture;
            DROP TABLE public.vms_blackwhite_person;
            DROP TABLE public.vms_blackwhite;
            DROP TABLE public.vms_area;
            DROP TABLE public.system_module_info;
            DROP TABLE public.system_client_info;
            DROP SEQUENCE public.seq_pers_wiegandfmtbid;
            DROP SEQUENCE public.seq_adms_devcmd;
            DROP SEQUENCE public.seq_acc_timesegid;
            DROP SEQUENCE public.seq_acc_dstimeid;
            DROP SEQUENCE public.seq_acc_deviceid;
            DROP SEQUENCE public.seq_acc_combopenpersonid;
            DROP SEQUENCE public.seq_acc_combopendoorid;
            DROP TABLE public.pers_wiegandfmt_bid;
            DROP TABLE public.pers_wiegandfmt;
            DROP TABLE public.pers_temp_person;
            DROP TABLE public.pers_position;
            DROP TABLE public.pers_personchange;
            DROP TABLE public.pers_person_link;
            DROP TABLE public.pers_person;
            DROP TABLE public.pers_leaveperson;
            DROP TABLE public.pers_issuecard;
            DROP TABLE public.pers_identity_card_info;
            DROP TABLE public.pers_certificate;
            DROP TABLE public.pers_card;
            DROP TABLE public.pers_biotemplate;
            DROP TABLE public.pers_attribute_ext;
            DROP TABLE public.pers_attribute;
            DROP TABLE public.hep_transaction;
            DROP TABLE public.hep_autoexport;
            DROP TABLE public.data_source;
            DROP TABLE public.base_sysparam;
            DROP TABLE public.base_register;
            DROP TABLE public.base_print_template;
            DROP TABLE public.base_print_param;
            DROP TABLE public.base_oplog;
            DROP TABLE public.base_message;
            DROP TABLE public.base_media_file;
            DROP TABLE public.base_mail;
            DROP TABLE public.base_language;
            DROP TABLE public.base_lang_res;
            DROP TABLE public.base_dictionary_value;
            DROP TABLE public.base_dictionary;
            DROP TABLE public.base_dbbackup;
            DROP TABLE public.auth_user_role;
            DROP TABLE public.auth_user_dept;
            DROP TABLE public.auth_user_area;
            DROP TABLE public.auth_user;
            DROP TABLE public.auth_security_param;
            DROP TABLE public.auth_role_permission;
            DROP TABLE public.auth_role;
            DROP TABLE public.auth_permission;
            DROP TABLE public.auth_department;
            DROP TABLE public.auth_company;
            DROP TABLE public.auth_biotemplate;
            DROP TABLE public.auth_area;
            DROP TABLE public.auth_appmenus_children;
            DROP TABLE public.auth_appmenus;
            DROP TABLE public.auth_app;
            DROP TABLE public.auth_api_token;
            DROP TABLE public.att_trip;
            DROP TABLE public.att_transaction;
            DROP TABLE public.att_timing;
            DROP TABLE public.att_timeslot_breaktime;
            DROP TABLE public.att_timeslot;
            DROP TABLE public.att_tempsch_timeslot;
            DROP TABLE public.att_tempsch;
            DROP TABLE public.att_sign_address_area;
            DROP TABLE public.att_sign_address;
            DROP TABLE public.att_sign;
            DROP TABLE public.att_shift_timeslot;
            DROP TABLE public.att_shift;
            DROP TABLE public.att_record;
            DROP TABLE public.att_point;
            DROP TABLE public.att_personsch_shift;
            DROP TABLE public.att_personsch;
            DROP TABLE public.att_person;
            DROP TABLE public.att_overtime;
            DROP TABLE public.att_out;
            DROP TABLE public.att_leavetype;
            DROP TABLE public.att_leave;
            DROP TABLE public.att_holiday;
            DROP TABLE public.att_groupsch_shift;
            DROP TABLE public.att_groupsch;
            DROP TABLE public.att_group_person;
            DROP TABLE public.att_group;
            DROP TABLE public.att_device_option;
            DROP TABLE public.att_device_op_log;
            DROP TABLE public.att_device;
            DROP TABLE public.att_deptsch_shift;
            DROP TABLE public.att_deptsch;
            DROP TABLE public.att_day_card_detail;
            DROP TABLE public.att_cyclesch_shift;
            DROP TABLE public.att_cyclesch;
            DROP TABLE public.att_custom_rule_org;
            DROP TABLE public.att_custom_rule;
            DROP TABLE public.att_class;
            DROP TABLE public.att_break_time;
            DROP TABLE public.att_autoexport;
            DROP TABLE public.att_area_person;
            DROP TABLE public.att_adjust;
            DROP TABLE public.adms_product;
            DROP TABLE public.adms_pos_full_log;
            DROP TABLE public.adms_pos_buy_log;
            DROP TABLE public.adms_pos_allow_log;
            DROP TABLE public.adms_device_option;
            DROP TABLE public.adms_device;
            DROP TABLE public.adms_devcmd;
            DROP TABLE public.adms_cmd_id;
            DROP TABLE public.adms_auth_device;
            DROP TABLE public.adms_att_device_log;
            DROP TABLE public.adms_acc_device_log;
            DROP TABLE public.acc_verifymode_rule;
            DROP TABLE public.acc_transaction;
            DROP TABLE public.acc_topdoor_by_person;
            DROP TABLE public.acc_timeseg_bid;
            DROP TABLE public.acc_timeseg;
            DROP TABLE public.acc_reader_option;
            DROP TABLE public.acc_reader;
            DROP TABLE public.acc_person_verifymoderule;
            DROP TABLE public.acc_person_lastaddr;
            DROP TABLE public.acc_person_firstopen;
            DROP TABLE public.acc_person_combopenperson;
            DROP TABLE public.acc_person;
            DROP TABLE public.acc_map_pos;
            DROP TABLE public.acc_map;
            DROP TABLE public.acc_linkage_vid;
            DROP TABLE public.acc_linkage_trigger;
            DROP TABLE public.acc_linkage_media;
            DROP TABLE public.acc_linkage_inout;
            DROP TABLE public.acc_linkage_index;
            DROP TABLE public.acc_linkage;
            DROP TABLE public.acc_level_person;
            DROP TABLE public.acc_level_door;
            DROP TABLE public.acc_level_dept;
            DROP TABLE public.acc_level;
            DROP TABLE public.acc_interlock;
            DROP TABLE public.acc_holiday;
            DROP TABLE public.acc_firstopen;
            DROP TABLE public.acc_firstin_lastout;
            DROP TABLE public.acc_ext_device;
            DROP TABLE public.acc_dstime_bid;
            DROP TABLE public.acc_dstime;
            DROP TABLE public.acc_door_verifymoderule;
            DROP TABLE public.acc_door;
            DROP TABLE public.acc_device_verifymode;
            DROP TABLE public.acc_device_option;
            DROP TABLE public.acc_device_event;
            DROP TABLE public.acc_device_bid;
            DROP TABLE public.acc_device;
            DROP TABLE public.acc_combopenperson_bid;
            DROP TABLE public.acc_combopendoor_bid;
            DROP TABLE public.acc_combopen_person;
            DROP TABLE public.acc_combopen_door;
            DROP TABLE public.acc_combopen_comb;
            DROP TABLE public.acc_auxout;
            DROP TABLE public.acc_auxin;
            DROP TABLE public.acc_antipassback;
            DROP TABLE public.acc_alarm_monitor;
            DROP EXTENSION plpgsql;
            DROP SCHEMA public;
        ";
    }
}